name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      name: Checkout
    
    - name: Run pre-commit
      uses: clowdhaus/terraform-composite-actions/pre-commit@v1.6.0
      with:
        terraform-version: 1.2.0
        terraform-docs-version: v0.16.0
        args: "--all-files --color always --show-diff-on-failure"
